# This workflow runs edgetest on locopy @ 17:20 UTC Fridays.
# https://github.com/fdosani/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Copy files for locopy
        id: copy-files
        run: |
          cp tests/data/.locopyrc ~/.locopyrc
          cp tests/data/.locopy-sfrc ~/.locopy-sfrc
      - id: run-edgetest
        uses: fdosani/run-edgetest-action@v1.0
        with:
          edgetest-flags: '-c setup.cfg -r requirements.txt --export'
          base-branch: 'develop'
          skip-pr: 'false'