# This workflow runs edgetest on locopy @ 17:20 UTC Fridays.
# https://github.com/fdosani/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
  workflow_dispatch:
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Copy files for locopy
        id: copy-files
        run: |
          cp tests/data/.locopyrc ~/.locopyrc
          cp tests/data/.locopy-sfrc ~/.locopy-sfrc
      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@v1.5
        with:
          edgetest-flags: '-c pyproject.toml --export'
          base-branch: 'develop'
          skip-pr: 'false'
