# This workflow runs edgetest on locopy @ 17:20 UTC Fridays.
# https://github.com/fdosani/run-edgetest-action

name: Run edgetest
on:
  schedule:
    - cron: '35 17 * * 5'
  workflow_dispatch:
jobs:
  edgetest:
    runs-on: ubuntu-latest
    name: running edgetest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          ref: main
      - name: Copy files for locopy
        id: copy-files
        run: |
          cp tests/data/.locopyrc ~/.locopyrc
          cp tests/data/.locopy-sfrc ~/.locopy-sfrc
      - id: run-edgetest
        uses: edgetest-dev/run-edgetest-action@8ceeac94abe951d6b51305454bc6d0ff2096e2ec  # v1.7
        with:
          edgetest-flags: '-c pyproject.toml --export'
          base-branch: 'main'
          skip-pr: 'false'
          add-paths: 'pyproject.toml, requirements.txt'
